// @ts-nocheck
// This file maps Wails bindings to the window.fme interface expected by the Angular app.
// The wailsjs imports are generated by Wails at build time and won't resolve until then.

import {
    StartDaemon,
    SystemOpen,
    SystemShowItemInFolder,
    ExternalLink,
    FatalShutdown,
    AppVersion,
    FirstLaunchComplete,
} from '../wailsjs/go/main/App';
import { EventsOn, EventsEmit, EventsOff } from '../wailsjs/runtime/runtime';

const wailsBridge: FmeClient = {
    startDaemon: () => StartDaemon(),
    stopDaemon: () => Promise.resolve(),
    systemOpen: (path: string) => SystemOpen(path),
    systemShowItemInFolder: (path: string) => SystemShowItemInFolder(path),
    externalLink: (url: string) => ExternalLink(url),
    fatalShutdown: () => FatalShutdown(),
    appVersion: () => AppVersion(),
    firstLaunchComplete: () => FirstLaunchComplete(),
    on: (channel: string, callback: (...args: any[]) => void) => {
        EventsOn(channel, (...args: any[]) => callback(null, ...args));
        return {} as any;
    },
    send: (channel: string, ...args: any[]) => {
        EventsEmit(channel, ...args);
    },
    removeAllListeners: (channel: string) => {
        EventsOff(channel);
        return {} as any;
    },
};

window.fme = wailsBridge;
