version: '3'

vars:
  CLI_BINARY: filemoverexpress
  OUTPUT_DIR: ../../dist
  BUILD_VERSION: '{{.BUILD_VERSION | default "0.0.0-local-dev"}}'
  GO_LDFLAGS: '-s -w -X "main.Version=v{{.BUILD_VERSION}}"'
  GO_BUILD_FLAGS: -trimpath

tasks:
  build:
    desc: Build CLI for the current platform
    cmds:
      - task: build:target
        vars: { GOOS: '{{OS}}', GOARCH: '{{ARCH}}', OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}{{if eq OS "windows"}}.exe{{end}}' }

  build:all:
    desc: Build CLI for all platforms
    cmds:
      - task: build:target
        vars: { GOOS: darwin, GOARCH: amd64, OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}-darwin' }
      - task: build:target
        vars: { GOOS: darwin, GOARCH: arm64, OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}-darwin-arm64' }
      - task: build:target
        vars: { GOOS: linux, GOARCH: amd64, OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}-linux' }
      - task: build:target
        vars: { GOOS: linux, GOARCH: arm64, OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}-linux-arm64' }
      - task: build:target
        vars: { GOOS: windows, GOARCH: amd64, OUTPUT: '{{.OUTPUT_DIR}}/{{.CLI_BINARY}}.exe' }

  build:target:
    internal: true
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
      CGO_ENABLED: '0'
    cmds:
      - go build {{.GO_BUILD_FLAGS}} -ldflags '{{.GO_LDFLAGS}}' -o {{.OUTPUT}} main.go

  test:
    desc: Run Go CLI tests
    cmds:
      - go test -gcflags="all=-N -l" -short -v -cover -coverprofile coverage.out ./...
      - go tool cover -html coverage.out -o coverage.html

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run
