name: 'Lint GUI'
description: 'Runs ESLint for the Angular GUI component'

runs:
  using: 'composite'
  steps:
    - name: Run GUI lint
      working-directory: src/gui
      run: task lint
      shell: bash
