name: 'Lint CLI'
description: 'Runs golangci-lint for the Go CLI component'

runs:
  using: 'composite'
  steps:
    - name: Run CLI lint
      run: task lint
      working-directory: src/cli
      shell: bash
