package configkeys

// When updating these values, make sure to make the corresponding updates on the structs in types/configtypes/config.go
const (
	KeySeparator                                = "."
	General                                     = "general"
	GeneralNoSleep                              = General + KeySeparator + "no_sleep"
	GeneralRetryCount                           = General + KeySeparator + "retry_count"
	GeneralMaxActiveChecksums                   = General + KeySeparator + "max_active_checksums"
	GeneralMaxActiveTransfers                   = General + KeySeparator + "max_active_transfers"
	GeneralTargetBandwidth                      = General + KeySeparator + "target_bandwidth"
	Logging                                     = "logging"
	LoggingDirectory                            = Logging + KeySeparator + "directory"
	LoggingSeverity                             = Logging + KeySeparator + "severity"
	LoggingMaxSize                              = Logging + KeySeparator + "max_size"
	LoggingMaxAge                               = Logging + KeySeparator + "max_age"
	LoggingCompress                             = Logging + KeySeparator + "compress"
	Reports                                     = "reports"
	ReportsDirectory                            = Reports + KeySeparator + "directory"
	APIServer                                   = "api_server"
	APIServerEnabled                            = APIServer + KeySeparator + "enabled"
	APIServerTLSSettings                        = APIServer + KeySeparator + "tls_settings"
	APIServerTLSSettingsEnabled                 = APIServerTLSSettings + KeySeparator + "tls_settings_enabled"
	APIServerTLSSettingsCertificateFile         = APIServerTLSSettings + KeySeparator + "tls_settings_certificate_file"
	APIServerTLSSettingsKeyFile                 = APIServerTLSSettings + KeySeparator + "tls_settings_key_file"
	APIServerRemoteSettings                     = APIServer + KeySeparator + "remote_settings"
	APIServerRemoteSettingsEnabled              = APIServerRemoteSettings + KeySeparator + "enabled"
	APIServerRemoteSettingsPreSharedKey         = APIServerRemoteSettings + KeySeparator + "pre_shared_key"
	APIServerRemoteSettingsPorts                = APIServerRemoteSettings + KeySeparator + "ports"
	APIServerRemoteSettingsAddress              = APIServerRemoteSettings + KeySeparator + "address"
	APIServerBlockedPathList                    = APIServer + KeySeparator + "blocked_path_list"
	APIServerAllowedOrigins                     = APIServer + KeySeparator + "allowed_origins"
	APIServerPermissions                        = APIServer + KeySeparator + "permissions"
	APIServerPermissionsAllowUIConfiguration    = APIServerPermissions + KeySeparator + "allow_ui_configuration"
	APIServerPermissionsAllowLocalRenameDelete  = APIServerPermissions + KeySeparator + "allow_local_rename_delete"
	APIServerPermissionsAllowRemoteRenameDelete = APIServerPermissions + KeySeparator + "allow_remote_rename_delete"
	TransferProfiles                            = "protocols.s3.transfer_profiles"
	TransferProfilesName                        = "name"
	TransferProfilesBucket                      = "bucket"
	TransferProfilesRegion                      = "region"
	TransferProfilesProfile                     = "profile"
	TransferProfilesEndpoint                    = "endpoint"
	TransferProfilesFilter                      = "filter"
	TransferProfilesAutoTuning                  = "auto_tuning"
	TransferProfilesChecksums                   = "checksums"
	TransferProfilesChecksumsEnabled            = TransferProfilesChecksums + KeySeparator + "enabled"
	TransferProfilesChecksumsAlgorithm          = TransferProfilesChecksums + KeySeparator + "algorithm"
	TransferProfilesChunkSize                   = "chunk_size"
	TransferProfilesThreads                     = "threads"
	TransferProfilesMaxAge                      = "max_age"
	TransferProfilesAccelerated                 = "accelerated"
	TransferProfilesFileOrder                   = "file_order"
	TransferProfilesEnableMetadataFilter        = "enable_metadata_filter"
	TransferProfilesStorageClass                = "storage_class"
	TransferProfilesPaths                       = "paths"
	TransferProfilesPathsLocal                  = TransferProfilesPaths + KeySeparator + "local"
	HotFolders                                  = TransferProfilesPaths + KeySeparator + "hot_folders"
)
